doc/api/BW.html
doc/howtos/howto-3.html
doc/howtos/howto-6.html
plugins/bw.js

Adds optional parameter to force the bandwidth plugin to block the beacon until it completes its test.  Added documentation where applicable as well to describe the behavior.

Optional parameter to await completion in bandwidth plugin before sending beacon

---

boomerang.js

error thrown as 'this.session' is undefined, when site_domain is provided as an option from config.
looking at the code this.session.domain is not used anywhere, so removing its ref.

this.session not defined

---

package.json

When running `npm install https://github.com/SOASTA/boomerang` the install script throws an error and fails because webdriver-manager does not exist. This update checks for the existence of webdriver-manager before attempting to run it.
Here is the error
```
npm ERR! boomerang@0.9.0 install: `node node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boomerang@0.9.0 install script 'node node_modules/protractor/bin/webdriver-manager update'.
npm ERR! This is most likely a problem with the boomerang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/protractor/bin/webdriver-manager update
npm ERR! You can get their info via:
npm ERR!     npm owner ls boomerang …
```

Fix npm error running webdriver-manager when it's not installed

---

package.json

Mocha is used as the test runner via `karma-mocha`. `karma-mocha` relies
on the availability of mocha as a peer dependency, but boomerang does
not define mocha as a dev dependency.

Add missing Mocha dev dependency

---

README.md
package.json

The build process was changed as part of the last big soasta contributions. We should update the docs to reflect the switch from Make to a Grunt based build process.

Update README to account for changed build procedure

---

plugins/errors.js

Without the compression plugin, you can't directly try to access
Compression.jsUrl and must first check for Compression itself. And
getErrorsForUrl should return the serialized errors.

Make the errors plugin work without the Compression plugin

---

plugins/usertiming.js
tests/page-templates/18-usertiming/04-usertiming-second-beacon.html
tests/page-templates/18-usertiming/04-usertiming-second-beacon.js
tests/page-templates/18-usertiming/05-usertiming-second-beacon-no-performance-now.html
tests/page-templates/18-usertiming/05-usertiming-second-beacon-no-performance-now.js

When using the User Timing API plugin, only the first beacon sent will include User Timing API data. Subsequent beacons will not collect newly set User Timing API data due to comparing incorrect timestamps.
To reproduce:
1. Add code to a test page running Boomerang and the User Timing API plugin. Something like the following would suffice:
```
performance.mark('pre-load-mark');
addEventListener('load', () => {
setTimeout(() => {
console.log('marking');
performance.mark('post-load-mark');
}, 5000);
});
```
2. Load the page with Boomerang, the User Timing API plugin and the sample code
3. After the `load` event fires, inspect the Network tab to see that a beacon was sent with the User Timing API data, including the 'pre-load-mark' mark. The 'post-load-mark' should not be present.
4. Fire …

Compare marks/measures to performance.now mark

---

plugins/mobile.js
tests/boomerang-test-framework.js
tests/page-templates/19-mobile/00-mobile-basic.html
tests/page-templates/19-mobile/00-mobile-basic.js
tests/page-templates/19-mobile/01-mobile-variable-mapping.html
tests/page-templates/19-mobile/01-mobile-variable-mapping.js
tests/page-templates/19-mobile/02-mobile-connection-disabled.html
tests/page-templates/19-mobile/02-mobile-connection-disabled.js

The Network Information API is a revision of the `navigator.connection` interface that attempts to provide a standard, cross-browser interface to access information about network conditions. This commit updates the mobile plugin to source network information from the newer source where
available.
This plugin works by first trying to find connection information from various places depending on the browser. It then tries to map data from the identified interface to variables that have historically been used by Boomerang. Effectively, this commit makes Boomerang aware of the new locations of information from the Network Information API.
Credit for this work goes to @bluesmoon, with assistance from @tollmanz to verify and write tests.

Add support for Network Information API

---

plugins/auto-xhr.js

While using the auto-xhr plugin, I have the following error: 
```
getBeaconURL is not a function
```
It seems that getBeaconURL is not defined.

Fix getBeaconURL error using auto-xhr plugin

---

plugins/usertiming.js
tests/page-templates/18-usertiming/00-usertiming-none.js
tests/page-templates/18-usertiming/01-usertiming-basic.js
tests/page-templates/18-usertiming/02-usertiming-polyfill.js
tests/page-templates/18-usertiming/03-usertiming-disabled.js
tests/page-templates/18-usertiming/04-usertiming-second-beacon.js
tests/page-templates/18-usertiming/05-usertiming-second-beacon-no-performance-now.js
tests/page-templates/18-usertiming/06-usertiming-no-compression.html
tests/page-templates/18-usertiming/06-usertiming-no-compression.js

Make compression optional by adding a configuration option
"ut_compression". When set to falsy, the usertiming plugin does not depend on
the usertiming-compression library, but sends the timings uncompressed
instead.
format for uncompressed send is json, example:
{"mark":{"foo":1234},{"measure":{"bar":5678,"baz":432}}

Optionally depend on usertiming-compression.

---

boomerang.js

Adds `beacon_with_credentials` to enable `xhr.withCredentials` and `beacon_disable_sendbeacon` to disable `sendBeacon()` support.

Boomerang: Optionally send XHR with credentials

---

plugins/angular.js
plugins/backbone.js
plugins/ember.js
plugins/history.js
plugins/spa.js

Clarifies the order that SPA plugins should be loaded.
https://github.com/akamai/boomerang/issues/209

JSDoc: Clarify SPA plugin load-order requirements

---

plugins/navtiming.js
tests/page-templates/19-navtiming/04-no-resend-after-complete.html
tests/page-templates/19-navtiming/04-no-resend-after-complete.js

only reset this.complete in clear if loadEventEnd is zero, which means
data was not fully sent in the last beacon.

Navigation Timing: Plugin sends twice per page

---

package-lock.json
package.json

**Description**
In this PR, I am just updating the version of `usertiming-compression` library from `0.1.8` to `0.1.9`. As a bug was fixed which could potentially break boomerang as the conversion of user-timings would fail for some cases. (More info here: https://github.com/nicjansma/usertiming-compression.js/pull/8)

UserTiming: Update usertiming-compression package to latest version

---

boomerang.js
tests/page-templates/25-cookie/02-cookie-from-new-session.js

**Description**
In this PR, I am fixing the following issue: https://github.com/akamai/boomerang/issues/273 
After this change `rt.si` will have a value of the form `UUID-(SessionStart in Base64)`. The `cookie.si` will only contain `UUID`. The reason for this is the cookie expires in 7 days whereas the session expires in 30 mins. Hence, for the session id: `UUID` will remain same for 7 days but a different session will identified by the `-(SessionStart in Base64)` suffix at the end.
The setting of `BOOMR.session.ID` is done in `BOOMR.init()`

Fix setting rt.si to UUID to fix the refreshing bug

---

.npmignore
Gruntfile.js

We need to publish `Gruntfile.js` to NPM and make a few changes to allow for files not published to NPM (e.g. the `tests/**` directory).
Addresses https://github.com/akamai/boomerang/issues/260

NPM: Allow running grunt build

---

plugins/continuity.js
tests/page-templates/21-continuity/17-tti-hero-images.html
tests/page-templates/21-continuity/33-tti-hero-images-bg-image.html
tests/page-templates/21-continuity/33-tti-hero-images-bg-image.js

Adding the possibility to detect background-image urls on elements containing the hero image selector. 
Example:
```
<div class="hero-image" />
div {
background: url('/image.png'); 
}
```
This should resolve #237.

Add support for background image detection for c.tti.hi

---

.github/workflows/node.js.yml
Gruntfile.js
package-lock.json
package.json
tests/e2e/e2e.js

In this PR, trying to tackle the following issue: https://github.com/akamai/boomerang/issues/276
- Adding Github Actions workflow on every commit push to the repository
- Adding new commands in `package.json` to be able to build, lint and test
- Upgrading `protractor: 5.4.4` to be able to run tests on latest chrome
- In, `Gruntfile.js` if `webDriverVersions` is not defined then the command becomes `webdriver-manager start undefined`. Fixing it such that if empty should not be applied to the command.
- Adding parallelization to the E2E-Test by using following environment variable: `CI_NODE_INDEX` and `CI_NODE_TOTAL`.

Build: Adding CICD Github Actions to every push to the repository

---

plugins/dns.js

Hi,
The current documentation of `plugins/dns.js` has link to Yahoo blog, which if you open they don't exist. The new link which I have added has the sufficient information to understand what the dns.js plugin does. The write up is from the same person who was in Yahoo before.
https://www.facebook.com/note.php?note_id=10150212498738920

DNS: Updated URL for docs

---

package.json

Fixes https://github.com/akamai/boomerang/issues/313
* Changes from `install` to `postinstall`, so we can depend on the local installation.
* Splits commands into two NPM scripts: `bower-install` and `webdriver-manager-update`, so NPM can handle the relative paths 
`./node_modules/.bin/` OK (when combined with `&&` it wasn't working for the second command on Windows).

package.json: Fix install/postinstall to use non-global scripts and be platform independent

---

plugins/spa.js

Make sure loop variable `i` is declared before using it so it doesn't become a global.
Closes #342

SPA: Lint: Fix incorrectly globally exported variable
